// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication8.Data;

#nullable disable

namespace WebApplication8.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901205017_SeedProducts2")]
    partial class SeedProducts2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication8.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<int>("oldPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "images/product/large-size/1.jpg",
                            Name = "Accusantium Dolorem1",
                            Price = 46.80m,
                            Qty = 1,
                            discount = 7,
                            oldPrice = 50
                        },
                        new
                        {
                            Id = 2,
                            Image = "images/product/large-size/2.jpg",
                            Name = "Mug Today Is A Good Day",
                            Price = 71.80m,
                            Qty = 2,
                            discount = 5,
                            oldPrice = 77
                        },
                        new
                        {
                            Id = 3,
                            Image = "images/product/large-size/3.jpg",
                            Name = "Accusantium Dolorem1",
                            Price = 46.80m,
                            Qty = 3,
                            discount = 0,
                            oldPrice = 0
                        },
                        new
                        {
                            Id = 4,
                            Image = "images/product/large-size/4.jpg",
                            Name = "Mug Today Is A Good Day",
                            Price = 71.80m,
                            Qty = 4,
                            discount = 0,
                            oldPrice = 0
                        },
                        new
                        {
                            Id = 5,
                            Image = "images/product/large-size/5.jpg",
                            Name = "Accusantium Dolorem1",
                            Price = 46.80m,
                            Qty = 5,
                            discount = 4,
                            oldPrice = 50
                        },
                        new
                        {
                            Id = 6,
                            Image = "images/product/large-size/6.jpg",
                            Name = "Mug Today Is A Good Day",
                            Price = 71.80m,
                            Qty = 6,
                            discount = 0,
                            oldPrice = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
